### ISSUE TITLE
Try building it from scratch and report back

### ISSUE THREAD

**Issue by jcklpe** [Agentic-Collaborative-Wiki-HAI/mono-repo#7]
If Wiki.js turns out to be a bad fit, what would building it ourselves cost?

Rough shape from prior discussion: **Vue** (not React, not Next.js), Supabase or plain Postgres, Markdown-compatible storage, and an editor that feels closer to Typora than a raw textarea — Milkdown/Crepe is one candidate.

**Explicitly not in scope:** real-time multi-cursor collaboration or CRDTs. Not building Google Docs.

Get far enough to judge the effort honestly against the Wiki.js spike — enough of a shell to know whether "build it ourselves" means two weekends or six.

Worth a spike doc in `docs/active-spikes/`.

Pairs with the Wiki.js spike; the two should compare notes rather than work in isolation.
